---
- name: debug
  hosts: all
  gather_facts: false
  connection: local

  tasks:

  #- debug:
  #    msg: "Group names are {{ hostvars[inventory_hostname].group_names[0]   }}"

  - debug:
      var: "{{ hostvars[item].ansible_host }}"
    with_inventory_hostnames:
    - all

  - lineinfile:
      path: /etc/hosts
      line: '{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname}}.{{ domain }}'
    with_inventory_hostnames:
    - all
      