---
- name: Setup VMs
  hosts: all
  connection: local
  gather_facts: no


  vars:
    - state: "poweredoff"
  vars_files:
    - "vars/vm-size/{{size}}.yaml"
    - "vars/environment/{{env}}.yaml"
 
  tasks:

    - debug:
        msg: "State before power off value is  {{ state }}"

    - name: power off VMs
      include_role:
        name: deploy-vsphere-template
      vars:
        state: "poweredoff"

    - debug:
        msg: "State after power off value is  {{ state }}"

    - name: delete VMs
      include_role:
        name: deploy-vsphere-template
      vars:
        state: "absent"
      become:

    - debug:
        msg: "State after delete VMs value is  {{ state }}"