---
- name: Setup VMs
  hosts: all
  #connection: local
  gather_facts: no



  vars_files:
    - "vars/vm-size/{{size}}.yaml"
    - "vars/environment/chc.yaml"
 

  tasks:

    - name: return motd to registered var
      command: git rev-parse HEAD
      register: gitCommitHash
      delegate_to: localhost

    - name: get remote git repo
      command: git config --get remote.origin.url
      register: gitRemote
      delegate_to: localhost

    - name: power on VMs
      include_role:
        name: deploy-vsphere-template
      vars:
        state: "poweredon"


