---
- name: Setup VMs
  hosts: all
  #connection: local
  gather_facts: no

  ### README
  ## To run:
  ## ansible-playbook -i phx.ini deploy-kubernetes-prod.yml --vault-id @prompt -e "env=phx" -K
  

  vars_files:
    - "vars/vm-size/{{size}}.yaml"
    - "vars/environment/{{env}}.yaml"
 

  tasks:

    - name: return motd to registered var
      command: git rev-parse HEAD
      register: gitCommitHash
      delegate_to: localhost

    - name: get remote git repo
      command: git config --get remote.origin.url
      register: gitRemote
      delegate_to: localhost

    - name: power on VMs
      include_role:
        name: deploy-vsphere-template
      vars:
        state: "poweredon"


