---
- name: Label OpenShift nodes
  hosts: workers
  connection: local
  gather_facts: no

  tasks:

  - name: label node
    command: "oc label node {{inventory_hostname}}.uka.topia.nz cryptopia.symbol/{{symbol}}=true"
    delegate_to: 127.0.0.1
