---
- name: Label OpenShift nodes
  hosts: workers
  connection: local
  gather_facts: no

  tasks:

  - name: label node
    command: oc label node {{inventory_hostname}}.topia.nz cryptopia.symbol/{{symbol}}=true
