---
- name: Initial setup of node
  hosts: all
  gather_facts: yes

  #### README
  ## Run:
  ## ansible-playbook -i phx.ini prepare-nodes.yaml --ask-pass --ask-become-pass

  tasks:

  - name: Set authorized key taken from file
    authorized_key:
      user: deploy
      state: present
      key: "{{ lookup('file', '/home/deploy/.ssh/id_rsa.pub') }}"
    become: true

  - hostname:
      name: '{{ inventory_hostname }}.{{domain}}'
    become: true