---
- name: Setup SSH for new VMs
  hosts: mgmt01.uka.topia.nz
  gather_facts: yes


  vars:
    - openshift_client: openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit

### Readme
## To run
## ansible-playbook install-ansible.yaml -i jumphost.ini -K
  tasks:

  - import_role:
       name: epel-repository

       
  - name: Install a list of packages
    yum:
      name:
        - ansible
        - epel-release
        - python-pip
        - policycoreutils-python
      state: present
    become: true

  - pip:
      name: ['pyvmomi', 'ansible']

  ## download https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  ## if not existing

  - name: "Extract {{openshift_client}}.tar.gz into /usr/bin/oc"
    unarchive:
      src: "https://github.com/openshift/origin/releases/download/v3.11.0/{{openshift_client}}.tar.gz"
      dest: /usr/bin
      remote_src: yes
    become: true
  
  - name: Move oc
    command: mv /usr/bin/{{openshift_client}}/oc /usr/bin/oc

  - name: Move kubectl
    command: mv /usr/bin/{{openshift_client}}/kubectl /usr/bin/kubectl

  - name: "Clean {{openshift_client}} path"
    file:
      state: absent
      path: "/usr/bin/{{openshift_client}}/"

    