---
- name: Initial setup of node
  hosts: all
  gather_facts: yes

  #### README
  ## Run:
  ## ansible-playbook -i phx.ini prepare-nodes.yaml --ask-pass --ask-become-pass

  tasks:


  - selinux:
        policy: targeted
        state: enforcing

  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release
      - python-pip
    become: true

  - name: Set authorized key taken from file
    authorized_key:
      user: deploy
      state: present
      key: "{{ lookup('file', '/home/deploy/.ssh/id_rsa.pub') }}"
    become: true

  - hostname:
      name: '{{ inventory_hostname }}.{{domain}}'
    become: true

  - lineinfile:
      path: /etc/hosts
      line: '{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname}}.{{ domain }}'
    with_inventory_hostnames:
    - all